---
- hosts: test
  remote_user: root
  gather_facts: no 
  roles:
    - {role: linux_facts}

- hosts: local
  roles:
    - {role: anchor_redis, taskname: 'updateMacip_linsol'} # This covers both Linux/Solaris hosts

#- hosts: test
#  roles:
#    - linux_facts
#    - esxi_facts
#    - render
