- name: Update Linux/Solaris hosts' Mac:IP pair in Redis
  anchor_redis:
#    login_host: 'localhost'      
#    login_port: 6379
    db: 0
    command: set
    key: "{{hostvars[item]['ansible_default_ipv4']['address']}}"
    value: "{{hostvars[item]['ansible_default_ipv4']['macaddress']}}" 
  with_items:
    - "{{groups['test']}}"
  when:
    - hostvars[item]['ansible_default_ipv4'] is defined
    - hostvars[item]['ansible_default_ipv4']['address'] != '0.0.0.0'
